base: &base
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('PGHOST') { 'db' } %>
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 20 } %>

development:
  <<: *base
  database: fae_dummy

test:
  <<: *base
  database: 'fae_dummy_test'
  username: postgres
  password: password
  host: <%= ENV.fetch('PGHOST') { 'db' } %>


remote_development:
  <<: *base
  database: fae_dev
  username: fae
  password: sh45&rEDnap

stage:
  <<: *base
  database: fae_stage
  username: fae
  password: sh45&rEDnap

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>